#development:
  #adapter: postgresql
  #encoding: unicode
  #database: tourist_development
  #pool: 5
  #username: aabazov
  #password:

#test:
  #adapter: postgresql
  #encoding: unicode
  #database: tourist_test
  #ool: 5
  #username: aabazov
  #password:

#production:
  #adapter: postgresql
  #encoding: unicode
  #database: tourist_production
  #pool: 5
  #username: aabazov
  #password:

development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: root  
  database: tourist_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: tourist_test

production: &production
  adapter: mysql2
  host: localhost
  database: tourist_production
  username: root
  password: root