development:
  adapter: postgresql
  encoding: unicode
  database: tourist_development
  pool: 5
  username: aabazov
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tourist_test
  pool: 5
  username: aabazov
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tourist_production
  pool: 5
  username: aabazov
  password:
